spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    content-type: text/html
server:
  port: 60000
  servlet:
    session:
      timeout: 3600000
#配置日志
logging:
  #配置日志文件路径
  path: .\log
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
